# Dependabot version
version: 2
 
# Define private registry
registries:
  # Unique name for  Cloudsmith registry
  cloudsmith-repo:
    type: pub-repository
    # Repositoru URL at Cloudsmith
    url: https://dart.cloudsmith.io/kamoromaximaintegra/flutter-package
    # Token that saved at Cloudsmith
    token: ${{secrets.CLOUDSMITH_TOKEN}}

# Konfigurasi pembaruan dependensi
updates:
  # Konfigurasi untuk ekosistem pub (Dart/Flutter)
  - package-ecosystem: "pub"
    # Lokasi file pubspec.yaml Anda (root direktori)
    directory: "/"
    # Jadwal pengecekan (misalnya, setiap hari)
    schedule:
      interval: "daily"
    # Memberi tahu Dependabot untuk menggunakan registry privat yang sudah kita definisikan di atas
    registries:
      - cloudsmith-repo
